on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: code check

# make sure CI fails on warnings
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clippy check
        run: |
          make check
  code_test:
    runs-on: ubuntu-latest
    needs: code_check
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          sudo apt-get install -y tree
      - name: functional tests
        run: |
          make functional-test
  code_bench:
    runs-on: ubuntu-latest
    needs: code_test
    steps:
      - uses: actions/checkout@v4
      - name: benchmark application
        run: |
          make benchmark
